const assert = require("assert")
const fs = require("fs")

const app = fs.readFileSync("admin/src/App.tsx", "utf8")
const accounts = fs.readFileSync("admin/src/pages/Accounts.tsx", "utf8")
const playerDetail = fs.readFileSync("admin/src/pages/PlayerDetail.tsx", "utf8")
const dashboard = fs.readFileSync("admin/src/pages/Dashboard.tsx", "utf8")
const adminMain = fs.readFileSync("admin/src/main.tsx", "utf8")
const adminStyles = fs.readFileSync("admin/src/styles.css", "utf8")
const serverApi = fs.readFileSync("src/routes/web_api/server.ts", "utf8")

assert.match(app, /label: "账号 \/ 存档"/)
assert.doesNotMatch(app, /label: "存档管理"/)
assert.doesNotMatch(app, /path="\/saves"/)

assert.match(accounts, /title="账号管理"/)
assert.doesNotMatch(accounts, /全部玩家/)
assert.match(accounts, /title="账号 \/ 存档"/)
assert.match(accounts, /账号 ID（viewer_id）/)
assert.match(accounts, /设备 ID/)
assert.match(accounts, /备注/)
assert.match(accounts, /搜索账号 ID、设备 ID、备注或存档/)
assert.match(accounts, /\/api\/server\/device\/rename/)
assert.match(accounts, /确认覆盖存档/)
assert.match(accounts, /apiUpload<\{ ok: boolean \}>/)
assert.match(accounts, /建议先导出备份/)
assert.match(accounts, /<Drawer/)
assert.match(accounts, /defaultPageSize: 20/)
assert.match(accounts, /删除未备注账号/)
assert.match(accounts, /DELETE_UNNOTED_ACCOUNTS/)
assert.match(accounts, /player\.isActive/)
assert.match(accounts, /执行前服务端会创建完整数据库备份/)
assert.match(accounts, /只保留本次清理备份/)
assert.match(accounts, /deleteUnnotedAccounts\/status/)
assert.match(accounts, /后台清理中/)
assert.match(accounts, /Worker/)
assert.match(accounts, /<Progress/)

assert.doesNotMatch(playerDetail, /玩家摘要/)
assert.match(playerDetail, /高级：直接添加/)
assert.match(playerDetail, /绕过抽卡、邮件领取和相关统计/)
assert.match(playerDetail, /存档时间（高级兼容设置）/)
assert.match(playerDetail, /timeOffset/)
assert.match(playerDetail, /确认覆盖存档/)
assert.match(playerDetail, /此操作无法在面板内撤销/)

assert.match(serverApi, /playerIds\.includes\(savedDefaultPid\)/)
assert.match(serverApi, /saveAccountDefaultPlayer\(accountId, remainingPlayerIds\[0\]\)/)
assert.match(serverApi, /viewerId: viewerSession \? String\(viewerSession\.token\) : null/)
assert.match(serverApi, /deviceId: binding\.device_id/)
assert.match(serverApi, /note: binding\.name/)
assert.match(serverApi, /deleteUnnotedAccounts/)
assert.match(serverApi, /Confirmation token is required/)
assert.match(serverApi, /selectUnnotedAccountIds/)
assert.match(serverApi, /startAccountCleanupWorker/)
assert.match(serverApi, /ACCOUNT_CLEANUP_BATCH_SIZE = 5/)
assert.match(serverApi, /new Worker/)
assert.match(serverApi, /deleteUnnotedAccounts\/status/)

assert.match(dashboard, /创建完整备份/)
assert.match(dashboard, /\/api\/server\/databaseBackup/)
assert.match(dashboard, /手动备份自动保留最近 5 份/)
assert.match(serverApi, /getDb\(\)\.backup/)
assert.match(serverApi, /MANUAL_DATABASE_BACKUP_KEEP_COUNT = 5/)
assert.match(serverApi, /removeExpiredManualDatabaseBackups/)
assert.match(adminMain, /colorBgContainer: dark \? "#10182a" : "#ffffff"/)
assert.match(adminMain, /colorText: dark \? "#f7fbff" : "#172033"/)
assert.match(adminStyles, /--admin-surface: #ffffff/)
assert.match(adminStyles, /--admin-text: #172033/)

console.log("admin-account-save-ui tests passed")
