"""Build the community API's trusted ID catalogue from a sanitized Wiki snapshot."""
import argparse
import json
import re
from pathlib import Path


def build_catalog(snapshot):
    characters, equipment = {}, {}
    elements = ["火", "水", "雷", "风", "光", "暗", "无"]
    for item in snapshot["characters"]:
        key = item["id"]
        if not re.fullmatch(r"c[0-9a-f]{12}", key) or key in characters:
            raise ValueError("角色必须使用唯一公开图鉴 ID")
        if item["element"] not in elements:
            raise ValueError("角色属性不在支持范围内")
        name, variant = item.get("name", ""), item.get("theme", "")
        if not isinstance(name, str) or not isinstance(variant, str):
            raise ValueError("公开角色姓名和版本必须是文字")
        characters[key] = {"element": item["element"], "name": name, "variant": variant}
    for item in snapshot["equipment"]:
        key = item["id"]
        if not re.fullmatch(r"w[0-9a-f]{12}", key) or key in equipment:
            raise ValueError("武器必须使用唯一公开图鉴 ID")
        equipment[key] = {"soul": bool(item.get("soul", {}).get("available"))}
    if not characters or not equipment:
        raise ValueError("社区目录不能使用空快照")
    return {"version": snapshot.get("meta", {}).get("version", ""), "elements": elements,
            "characters": characters, "equipment": equipment}


def main():
    parser = argparse.ArgumentParser(description="从脱敏 Wiki 快照生成社区验证目录")
    parser.add_argument("snapshot", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    data = build_catalog(json.loads(args.snapshot.read_text(encoding="utf-8")))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("// Generated by wf_wiki_community_catalog.py; public IDs only.\nexport default "
                           + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n", encoding="utf-8")
    print(f"社区验证目录：{len(data['characters'])} 角色，{len(data['equipment'])} 武器")


if __name__ == "__main__":
    main()
