import test from 'node:test';
import assert from 'node:assert/strict';
import {context, submission} from './helpers.mjs';
import {GAME_CODE_PATTERN} from '../game-codes.mjs';
test('只有管理员生成高熵原生格式码，相同阵容复用且公开返回最小字段', async (t) => {
  const app = context(); t.after(() => app.close()); await app.admin(); const id = (await app.create()).json.team.id;
  const created = await app.call(`/admin/teams/${id}/game-code`, {body: {expectedRevision: 1}});
  assert.equal(created.status, 200); assert.match(created.json.gameCode, GAME_CODE_PATTERN);
  const repeated = await app.call(`/admin/teams/${id}/game-code`, {body: {expectedRevision: 1}});
  assert.equal(repeated.json.gameCode, created.json.gameCode); assert.equal(repeated.json.teamRevision, 1);
  assert.equal(app.db.raw.prepare("SELECT count(*) AS n FROM community_audit WHERE action='game_code_create'").get().n, 1);
  const found = (await app.call(`/game-codes/${created.json.gameCode}`)).json;
  assert.deepEqual(Object.keys(found).sort(), ['active', 'team', 'title']); assert.deepEqual(found.team, submission().team);
  assert.equal((await app.call('/teams')).json.items[0].gameCode, created.json.gameCode);
  app.cookie = '';
  assert.equal((await app.call(`/admin/teams/${id}/game-code`, {body: {expectedRevision: 1}})).status, 401);
});
test('隐藏、阵容修改和撤销均使游戏码不可查询；恢复后可按当前阵容另生成', async (t) => {
  const app = context(); t.after(() => app.close()); await app.admin(); const id = (await app.create()).json.team.id;
  const make = (revision) => app.call(`/admin/teams/${id}/game-code`, {body: {expectedRevision: revision}});
  const code = (await make(1)).json.gameCode;
  await app.call(`/admin/teams/${id}`, {method: 'PATCH', body: {expectedRevision: 1, status: 'hidden'}});
  assert.equal((await app.call(`/game-codes/${code}`)).status, 404); assert.equal((await make(2)).status, 409);
  const changed = submission(); changed.team.unison[0] = 'c6';
  await app.call(`/admin/teams/${id}`, {method: 'PATCH', body: {...changed, expectedRevision: 2, status: 'approved'}});
  assert.equal((await app.call(`/game-codes/${code}`)).status, 404);
  const next = (await make(3)).json.gameCode; assert.notEqual(next, code);
  await app.call(`/admin/teams/${id}`, {method: 'PATCH', body: {title: '只改标题', expectedRevision: 3}});
  assert.equal((await app.call(`/game-codes/${next}`)).json.title, '只改标题');
  assert.equal((await app.call(`/admin/teams/${id}/game-code/revoke`, {body: {expectedRevision: 4}})).json.active, false);
  assert.equal((await app.call(`/game-codes/${next}`)).status, 404);
  assert.equal((await app.call('/teams')).json.items[0].gameCode, null);
  assert.notEqual((await make(4)).json.gameCode, next);
});
test('真实SQLite并发生成只出现一个有效队伍码且一次审计', async (t) => {
  const app = context(); t.after(() => app.close()); await app.admin(); const id = (await app.create()).json.team.id;
  const responses = await Promise.all(Array.from({length: 15}, () => app.call(`/admin/teams/${id}/game-code`, {body: {expectedRevision: 1}})));
  assert.ok(responses.every((r) => r.status === 200));
  assert.equal(new Set(responses.map((r) => r.json.gameCode)).size, 1);
  assert.equal(app.db.raw.prepare("SELECT count(*) AS n FROM community_audit WHERE action='game_code_create'").get().n, 1);
  assert.equal((await app.call(`/admin/teams/${id}/game-code`, {body: {expectedRevision: 0}})).status, 409);
  assert.equal((await app.call('/game-codes/not-a-code')).status, 404);
});
test('A到B再到A及隐藏恢复都不能复活旧码，失败并发编辑不能撤销胜方码', async (t) => {
  const app = context(); t.after(() => app.close()); await app.admin(); const id = (await app.create()).json.team.id;
  const make = (revision) => app.call(`/admin/teams/${id}/game-code`, {body: {expectedRevision: revision}});
  const change = (body) => app.call(`/admin/teams/${id}`, {method: 'PATCH', body});
  const codeA = (await make(1)).json.gameCode;
  const changed = submission(); changed.team.unison[0] = 'c6';
  await change({...changed, expectedRevision: 1});
  await change({...submission(), expectedRevision: 2});
  assert.equal((await app.call(`/game-codes/${codeA}`)).status, 404);
  const codeNew = (await make(3)).json.gameCode; assert.notEqual(codeNew, codeA);
  await change({status: 'hidden', expectedRevision: 3});
  await change({status: 'approved', expectedRevision: 4});
  assert.equal((await app.call(`/game-codes/${codeNew}`)).status, 404);
  const finalCode = (await make(5)).json.gameCode;
  assert.equal((await change({title: '新标题', expectedRevision: 5})).status, 200);
  assert.equal((await change({status: 'hidden', expectedRevision: 5})).status, 409);
  assert.equal((await app.call(`/game-codes/${finalCode}`)).status, 200);
});
